"""add : new column in users table named role

Revision ID: 51043f4d9b17
Revises: f69433e4e35c
Create Date: 2025-02-06 13:36:01.534407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51043f4d9b17'
down_revision = 'f69433e4e35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'collector', name='userroleenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
